### PR TITLE
Apache config tweaks

### PR DESCRIPTION
**Pull request by mkszuba**
A bunch of changes to _webvm_ Apache configuration which remove some unnecessary things and hopefully align it more with the Ensembl way of deploying things. Please see respective commit messages for details.

### CODE REVIEW

**Comment by s-mm** [comment]
@Helpdesk- I will be setting up a new server for NoMerge testing which will be a good opportunity to test these changes. Please merge this PR only after these changes have been tested.

**Review by tgrego — APPROVED** [review]
I'm ok with this after said testing.

**Review by s-mm — COMMENTED** [review]
When I tried starting/stopping the server after checking out this branch, I get the error-
apache2: Configuration error: No MPM loaded. 

This is on a KUbuntu machine.

**Comment by mkszuba** [comment]
I'll look into this. Which version? Of both KUbuntu and Apache.

**Comment by s-mm** [comment]
KUbuntu 16.04
Apache 2.4.18

**Comment by mkszuba** [comment]
OK, looks like at least on some systems it remains necessary to explicitly load an MPM. Could you try now?

**Comment by s-mm** [comment]
Works now. Approved.

**Review by s-mm — APPROVED** [review]

**Pull request merged**
